# Generated by Django 5.1.1 on 2025-02-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_five',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_four',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_one',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_six',
            new_name='photo_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_three',
            new_name='photo_5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_two',
            new_name='photo_6',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='sqfeet',
            new_name='sqft',
        ),
    ]
