# Generated by Django 5.1.1 on 2025-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_photo_five_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='photo_five',
        ),
    ]
