# Generated by Django 5.1.1 on 2025-02-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_photo_5_listing_photo_five'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_five',
            new_name='photo_5',
        ),
    ]
