# Generated by Django 5.1.1 on 2025-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_photo_five_listing_photo_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_five',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
